### DISCUSSION TITLE
UUIDs broken for me in 0.11.0

### DISCUSSION THREAD

**Discussion by will-hart** [SeaQL/sea-orm#1489] [Q&A]
I have a `sea-orm` based API server that works perfectly with `sea-orm = "0.10.7"`. I'm using a cargo workspace. The root `Cargo.toml` has

```toml
sea-orm = { version = "0.10.7", features = [ "runtime-tokio-rustls", "sqlx-postgres", "macros", "with-uuid" ] }
```

If I make the following diff, `Uuid::new_v4()` is no longer defined:

```diff
-sea-orm = { version = "0.10.7", features = [ "runtime-tokio-rustls", "sqlx-postgres", "macros", "with-uuid" ] }
+sea-orm = { version = "0.11.0", features = [ "runtime-tokio-rustls", "sqlx-postgres", "macros", "with-uuid" ] }
```

The error I get is 

```bash
error[E0599]: no function or associated item named `new_v4` found for struct `sea_orm::prelude::Uuid` in the current scope
  --> db\src\mutations\my_query.rs:55:27
   |
55 |             id: Set(Uuid::new_v4()),
   |                           ^^^^^^ function or associated item not found in `sea_orm::prelude::Uuid`
```

Am I missing something? I don't see anything relevant in the release notes and I can't see any obvious changes in the repo. 

---

## EDIT

I got it to compile by specifying the uuid crate as a dependency, but I'm still confused why this was working before 😆 

```toml
[workspace.dependencies.uuid]
# Make sure that this version stays in sync with sea-orm's version
version = "1.2.2"
features = ["std", "v4"]
```
