### ISSUE TITLE
Very high CPU usage during build, antivirus flagged target dir as malware

### ISSUE THREAD

**Issue by broomlytinum** [SeaQL/sea-orm#1113]
I went to build SeaORM as a dependency in a fresh crate with the following in my `Cargo.toml`:

```toml
[dependencies]
sea-orm = { version = "0.9.3", features = ["runtime-tokio-native-tls", "sqlx-postgres", "macros"] }
```

Compilation began to eat up my CPU, nearing 100% usage between my terminal and rust-analyzer in VSCode. Moments after I attempted a `cargo clean`, McAfee claimed there was a virus in my crate's target folder and requested a restart. Unfortunately I did not catch a glimpse of the filename before I restarted, so this may not be of much help if it turns out irreproducible... 😅
