### ISSUE TITLE
Cannot clone `DatabaseConnection` when the `mock` flag is enabled.

### ISSUE THREAD

**Issue by troglodytto** [SeaQL/sea-orm#1744]
## Description

When using the mock feature, the implementation of "Clone" on the struct "DatabaseConnection" is removed, and hence, the program fails to compile in situations where it must be Clone-able, for example, using the Database connection as a Data-source in actix

## Steps to Reproduce

```rust
// src/main.rs

use actix_web::{App, HttpServer};
use sea_orm::{ConnectOptions, Database};

#[actix_web::main]
async fn main() {
    // Your database connection string here
    let conn_opts = ConnectOptions::new("protocol://username:password@host/database".to_owned());

    let conn = Database::connect(conn_opts).await.unwrap();

    HttpServer::new(move || App::new().app_data(conn.clone()))
        .bind("127.0.0.1:8080")
        .unwrap();
}

#[cfg(test)]
mod test {
    use sea_orm::{DatabaseBackend, MockDatabase};

    #[tokio::test]
    async fn test_mock() {
        let db = MockDatabase::new(DatabaseBackend::Postgres).into_connection();
    }
}

```

```toml
# Cargo.toml

[package]
name = "bug-report-min"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
sea-orm = { version = "0.11.3", features = ["sqlx-postgres", "macros", "runtime-actix-rustls", "mock"] }
tokio = { version = "1.29.1", features = ["full"] }
```

### Expected Behavior

The `DatabaseConnection` struct should be `Clone` whether or not the `mock` feature is enabled or not

### Actual Behavior
<details>
<summary>App fails to compile</summary>

When enabling the `mock` feature, the implementation of Clone is disabled

```
error[E0599]: no method named `clone` found for enum `sea_orm::DatabaseConnection` in the current scope
  --> src/main.rs:11:54
   |
11 |     HttpServer::new(move || App::new().app_data(conn.clone()))
   |                                                      ^^^^^ help: there is a method with a similar name: `close`
```

And when not enabling the mock feature, tests don't work (which is expected)

```
error[E0432]: unresolved import `sea_orm::MockDatabase`
  --> src/main.rs:18:36
   |
18 |     use sea_orm::{DatabaseBackend, MockDatabase};
   |                                    ^^^^^^^^^^^^
   |                                    |
   |                                    no `MockDatabase` in the root
   |                                    help: a similar name exists in the module: `Database`

```

</details>

### Reproduces How Often

Yes, It is always reproducible.

### Workarounds

No success yet, tried enabling different feature flags in different environments

## Reproducible Example
The aforementioned steps should be enough to reproduce the issue

## Versions
sea-orm v0.11.3
actix-web v4.3.1
rustc 1.70.0 (90c541806 2023-05-31)
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
Linux 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 GNU/Linux
