### ISSUE TITLE
debug log not work as expected

### ISSUE THREAD

**Issue by Baiyuetribe** [SeaQL/sea-orm#2010]
## Description
i read docs, https://www.sea-ql.org/SeaORM/docs/install-and-config/debug-log/
expected:
```sql
 SELECT `cake`.`id`, `cake`.`name` FROM `cake` LIMIT 1
 ```
bugs: 
```sql
INFO summary="DELETE FROM `downloads` WHERE …" db.statement="\n\nDELETE FROM\n  `downloads`\nWHERE\n  `downloads`.`created` < ?\n" rows_affected=0 rows_returned=0 elapsed=414.458µs
```
Incomplete mysql statement with missing parameters

## Steps to Reproduce
```rust
pub async fn main() {
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::DEBUG)
        .with_test_writer()
        .init();

    // ...
}
```

### Expected Behavior

How do I get the full mysql statement as written in the tutorial?

## Versions

latest

**Comment by tyt2y3** [comment]
You need to add the feature flag `debug-print` to Cargo.toml and disable sqlx_logging (as stated in the docs).

```toml
[dependencies.sea-orm]
path = "../../../" # remove this line in your own project
version = "0.12.6" # sea-orm version
features = [
    "debug-print", # <--
    "runtime-async-std-native-tls",
    # "sqlx-mysql",
    # "sqlx-postgres",
    "sqlx-sqlite",
]
```
