### ISSUE TITLE
sea-orm-cli cannot open SQLite db.

### ISSUE THREAD

**Issue by snaiperskaya96** [SeaQL/sea-orm#2262]
## Description
Hello, 
i'm running into this issue where `sea-orm-cli` does not seem to be able to open my DB file.
I'm generating the db and populating it via a programmatic migration so that part of the API seems fine.
Any idea?

## Steps to Reproduce

1. Generate a sqlite db.
![image](https://github.com/SeaQL/sea-orm/assets/5279281/1c247945-0b8c-4882-934d-d5ce16aaa5e2)
2. Interact with it to make sure seaql can pick it up
```rust
    let db = db::create_db_conn().await?; // 
    let _ = SchemaManager::new(&db); // <- This all work 
    Migrator::refresh(&db).await?; // 
```
3. Try to generate entities with the cli
```bash
sea-orm-cli generate entity -u sqlite://C:\\Users\\jury\\AppData\\Roaming\\skaya\\fluffy-waffle\\data\\db_debug.sqlite -o src/entities --with-serde both
```

### Expected Behavior
Entities are being generated and populated into src/entities

### Actual Behavior
```bash
Connecting to SQLite ...
error returned from database: (code: 14) unable to open database file
```

### Reproduces How Often
Always

### Workarounds
Haven't found any workaround so far.

## Versions
```toml
sea-orm = { version = "0.12.15", features = ["sqlx-sqlite", "runtime-async-std-native-tls"] }
sea-orm-migration = "0.12.15"
```
