### ISSUE TITLE
[BUG][SQLITE] Failed to find inserted item

### ISSUE THREAD

**Issue by GrandChaman** [SeaQL/sea-orm#244]
Hello!

Thank you for the great library!

I've run into a small problem. It seems there is a problem when inserting new data into a `Sqlite` database, in a table which primary key is a string.

I've tried using `WITHOUT ROWID` in the table definition, but no luck.

From a debug statement I added in a local version of `sea-orm`, it seems the "last inserted id" is defaulting to either `"0"` or `"1"`

Here is a minimal working example:

`main.rs`

```rust
use anyhow::Error;
use sea_orm::entity::prelude::*;
use sea_orm::entity::{Set, Unset};

mod database;

#[tokio::main]
async fn main() -> Result<(), Error> {
    let database = database::get_connection().await?;

    let new_repository = database::entities::repository::ActiveModel {
        id: Set("some_id".to_string()),
        name: Set("some_name".to_string()),
        owner: Set("some_owner".to_string()),
        description: Unset(None)
    };
    let res = new_repository.insert(&database).await?;
    println!("{:#?}", res);
    Ok(())
}
```

`Cargo.toml` (truncated)
```toml
[dependencies]
tokio = { version = "1", features = [ "full" ] }
anyhow = "1"
sea-orm = { version = "^0", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ], default-features = false }
```

The migration file

```sql
CREATE TABLE IF NOT EXISTS repository (
    id TEXT PRIMARY KEY,
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT
);
```

The entity file
```rust
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "repository")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: String,
    pub owner: String,
    pub name: String,
    pub description: Option<String>
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
}

impl ActiveModelBehavior for ActiveModel {}
```
