### ISSUE TITLE
`error[E0433]`: failed to resolve: use of undeclared crate or module `rocket_okapi`

### ISSUE THREAD

**Issue by sawa-ko** [SeaQL/sea-orm#2451]
## Description

When trying to use the `sea-orm-rocket` crate with the rocket_okapi feature the compiler throws an error that the `rocket_okapi` crate could not be found.

## Steps to Reproduce

1. Install `sea-orm-rocket` and `rocket_okapi`
2. Enable `rocket_okapi` feature in `sea-orm-rocket` crate
3. Compile and see error

```
error[E0433]: failed to resolve: use of undeclared crate or module `rocket_okapi`
  --> C:\Users\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\sea-orm-rocket-0.5.4\src\database.rs:13:5
   |
13 | use rocket_okapi::{
   |     ^^^^^^^^^^^^ use of undeclared crate or module `rocket_okapi`

```

### Expected Behavior

Work correctly, since the feature is supposed to enable something but the crate does not have that dependency in its `Cargo.toml`.

### Actual Behavior

Error compiling because the crate `rocket_okapi` is not found.

### Reproduces How Often

Always.

## Reproducible Example

Just add this to your `Cargo.toml`.

```toml
[dependencies]
rocket = { version = "0.5.1", features = ["serde_json", "secrets", "json"] }
sea-orm-rocket = { version = "0.5.4", features = ["rocket_okapi"] }
rocket_okapi = { version = "0.9.0", features = ["swagger", "rapidoc", "rocket_db_pools"] }
```

## Versions

rocket: `0.5.1`
sea-orm-rocket: `0.5.4`
rocket_okapi: `0.9.0`
