### ISSUE TITLE
Rename sea-orm-cli binary to sea-orm

### ISSUE THREAD

**Issue by tqwewe** [SeaQL/sea-orm#254]
The package `sea-orm-cli` can keep the same name under "package", but can be renamed to `sea-orm` in `[[bin]]`:
```toml
[package]
name = "sea-orm-cli"

[[bin]]
name = "sea-orm" # instead of "sea-orm-cli"
path = "src/main.rs"
```

This will change the built executable to be just called `sea-orm`, so commands can be ran with:
```bash
sea-orm generate entity
```

If this is not desired, feel free to close the issue :)
