### ISSUE TITLE
the trait `Clone` is not implemented for `DatabaseConnection`

### ISSUE THREAD

**Issue by RogueJin** [SeaQL/sea-orm#836]
I got the below error when I set a filed as DatabaseConnection type, but such usage works in rocket example, so is there anything I missed?

the trait bound `DatabaseConnection: Clone` is not satisfied the trait `Clone` is not implemented for `DatabaseConnection`

``` rust
#[derive(Clone)]
pub struct DbStruct {
    db_conn: DatabaseConnection
}
```

``` toml
[dependencies]
sea-orm = { version ="^0.8.0", features=["sqlx-postgres", "sqlx-sqlite","runtime-tokio-rustls"]}
```
