### ISSUE TITLE
Too much warnings when  compile code. 

### ISSUE THREAD

**Issue by baoyachi** [SeaQL/sea-orm#838]
When compile sea-orm.It's very uncomfortable for a programmer who likes not to warnings.

Suggestion: add clippy check in github action, when check code warnings compile not pass.
```
cargo clippy --all-targets --all-features -- -D warnings
```

**Comment by billy1624** [comment]
Hey @baoyachi, thanks for the initiatives! I agree we should have enforce clippy checks in CI. Please check https://github.com/SeaQL/sea-orm/pull/840

**Comment by baoyachi** [comment]
So good. I have some other suggestions：
* add `cargo fmt`
* add `cargo fix` && `cargo fix` 

use `cargo fix` twice，make ci check code git status is clean, `cargo fix` can check git is dirty ,compile error

detail see: [github action](https://github.com/baoyachi/shadow-rs/blob/master/.github/workflows/check.yml#L31-L36)

```yml
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Check fix
        run: cargo fix && cargo fix
      - name: Check with clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
```
