### ISSUE TITLE
Incomplete changelog

### ISSUE THREAD

**Issue by Jupp56** [SeaQL/sea-orm#891]
## Description

The changelog is incomplete in my opinion because it can happen that code using chrono data structures compiled in 0.8 that does not compile in 0.9.
The problem is that the with-chrono feature flag becomes explicit rather than implicit.

## Steps to Reproduce

Upgrade from 0.8 to 0.9, following just the changes of CHANGELOG.md

### Expected Behavior

Still works.

### Actual Behavior

Does not compile without changing feature flags.

### Reproduces How Often

always.

## Versions

0.9, postgres, rustc 1.62.0

## Additional Information

Example code/config that compiles on 0.8 but doesnt on 0.9.

Cargo.toml:
```toml
[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "^0.8", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros"], default-features = false }
serde = { version = "^1.0", features = [ "derive" ]}
chrono = { version="0.4", features = ["serde"]}
```
lib.rs:
```rust
pub use sea_orm;

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, PartialOrd, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "whatever")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub test: NaiveDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
```
