### ISSUE TITLE
Add more workspace setup information

### ISSUE THREAD

**Issue by sungvzer** [SeaQL/sea-orm#942]
## Motivation

As a newcomer, I found it difficult to make VSCode understand the code written in the `migration` folder. 

It is because the migration is not imported in the main crate.

## Proposed Solutions

1. Add functionality to `sea-orm-cli` to automatically add the following lines to the main `Cargo.toml`:
```toml
[dependencies]
sea-orm = {
    # ...
}

migration = { path = "/path/to/migration/crate" }

```
2. If 1 is not feasible, add some information about this in the documentation, preferably under the _Installation & Configuration_ section.

## Additional Information

The solution enables `rust-analyzer` to correctly identify the crate, while also providing auto-completion and code-checking.
